export interface FormAgeOfBots {
    carresFouille               : number,
    carresFouilleOk             : boolean,
    echantillonsPris            : number,
    echantillonsCampement       : number,
    echantillonsCampementValides: number,
    echantillonsGalerie         : number,
    echantillonsGalerieValides  : number,
    echantillonsAbri            : number,
    retourRobots                : boolean,
    statuettePresente           : boolean,
    statuettePrise              : boolean,
    statuettePosee              : boolean,
    repliquePosee               : boolean,
    vitrinePresente             : boolean,
    vitrineActivee              : boolean,
    estimation                  : number,
    nonForfait                  : boolean,
}